### ISSUE TITLE
Inappropriate repository contents.

### ISSUE THREAD

**Issue by WinterMute** [joel16/3DSFlash#1]
It's not the best of ideas to keep executables in your project, **especially** tools that are provided by devkitARM, like picasso.

https://github.com/joel16/3DSFlash/tree/master/tools

3dstool has no business in a homebrew project. makerom and bannertool should be in a path on your development machine accessible from where-ever you build the project. 

Please remove this folder and encourage others to keep these things separate from your project files. We do hope to add tools without the dubious provenance for producing CIAs to devkitARM in the near future.

**Comment by joel16** [comment]
Yes you're right. I've been meaning to change this for quite a while, it was just something I tried way back for an older project with Travis CI integration. I guess I never bothered to build CIA's the right away, and basically used the same makefile and the tools as a template for all my projects. I plan on changing this now, thanks for reminding me.

**Comment by joel16** [comment]
Alright done. https://github.com/joel16/3DSFlash/commit/768922171c6fcc218205cd175b10c20482b5fcbb

Also got rid of SF2D to make this homebrew more likely to be future proof, so it uses gfxFramebuffers instead.

Cheers
